
import { GoogleGenAI } from "@google/genai";

export class GeminiService {
  private ai: GoogleGenAI;

  constructor() {
    this.ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  }

  /**
   * Generates or edits an image using gemini-2.5-flash-image
   * @param imageBase64 The source image in base64 format (without data:image/... prefix)
   * @param mimeType The mime type of the source image
   * @param prompt The instructions for the transformation
   */
  async transformImage(imageBase64: string, mimeType: string, prompt: string): Promise<string> {
    const response = await this.ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: imageBase64,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
    });

    if (!response.candidates || response.candidates.length === 0) {
      throw new Error("No image generated by the AI.");
    }

    // Iterate through parts to find the generated image
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }

    throw new Error("The AI returned a text response instead of an image. Try a more specific prompt.");
  }
}

export const geminiService = new GeminiService();
